/* This file is autogenerated by generate-buildinfo.sh */

#ifndef _EXAHYPE_BUILD_INFO_H_
#define _EXAHYPE_BUILD_INFO_H_

#define EXAHYPE_BUILDINFO_AVAILABLE
#define EXAHYPE_BUILD_DATE          "Thu May 11 13:22:08 BST 2017"
#define EXAHYPE_BUILD_HOST          "jack-def2"

/* Strings passed by the Makefile */
#define EXAHYPE_BUILD_INFO \
    "COMPILER = GNU\n" \
    "MODE = Release\n" \
    "SHAREDMEM = None\n" \
    "DISTRIBUTEDMEM = None\n" \
    "------\n" \
    "ARCHITECTURE = CPU\n" \
    "CC = g++\n" \
    "BOUNDARYCONDITIONS = None\n" \
    "------\n" \
    "EXAHYPE_PATH = /home/jack/programming/uni/project/exahype/./ExaHyPE\n" \
    "PROJECT_PATH = /home/jack/programming/uni/project/exahype/./Demonstrators/NewCudaEulerFV\n" \
    "PEANO_KERNEL_PEANO_PATH = /home/jack/programming/uni/project/exahype/./Peano/peano\n" \
    "PEANO_KERNEL_TARCH_PATH = /home/jack/programming/uni/project/exahype/./Peano/tarch\n" \
    ""


/*
 * ExaHyPE Git Repository information extraction
 */

/* Information collected with git version 2.7.4 */
#define EXAHYPE_GIT_INFO "master  0c4bf7d Sun Mar 26 23:16:53 2017"

/*
 * Peano Subversion Repository information extraction
 */

/* No svn repository found or svn binary not available */
#define PEANO_SVN_INFO "No svn/repository available"

#endif /* EXAHYPE_BUILD_INFO_H */
